{{- if not .Values.tls.shareFederatorSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "federator-secret"
  labels:
    wireService: federator
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
{{- if .Values.remoteCAContents }}
  ca.crt: {{ .Values.remoteCAContents | b64enc | quote }}
{{- end -}}
  # TODO: add validation and fail early during templating: either contents should be provided; or explicitly system trust store enabled
  {{- if .Values.clientPrivateKeyContents }}
  tls.key: {{ .Values.clientPrivateKeyContents | b64enc | quote }}
  {{- end -}}
  {{- if .Values.clientCertificateContents }}
  tls.crt: {{ .Values.clientCertificateContents | b64enc | quote }}
  {{- end -}}
{{- end -}}
