{{- if and .Values.tls.enabled .Values.tls.useCertManager -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: {{ required "Missing value: certmasterEmail" .Values.certManager.certmasterEmail | quote }}
    # NOTE: this secret doesnt need to be created, it only gets a name with this
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end -}}
